version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=your_db_user
      - DB_PASS=your_db_password
      - DB_HOST=your_db_host
      - DB_NAME=your_db_name
      - DB_PORT=5432
    depends_on:
      - postgres

  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: F!8VcuAFmZcJU4X
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: